# Generated by Django 2.2.9 on 2020-01-24 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('tel', models.IntegerField(verbose_name='전화번호')),
                ('addr', models.TextField(blank=True, verbose_name='주소')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제품명')),
                ('img', models.ImageField(blank=True, upload_to='images/', verbose_name='제품사진')),
                ('info', models.TextField(blank=True, verbose_name='제품설명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('amount', models.IntegerField(verbose_name='남은수량')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Company')),
            ],
        ),
    ]
