# Generated by Django 2.2.9 on 2020-01-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
    ]
