# Generated by Django 2.2.9 on 2020-01-28 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200124_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='stock.Company', verbose_name='거래처'),
        ),
    ]
